#!/usr/bin/env sh
set -e
dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
. $dir/../common/util
. $dir/../config
scriptname="Post system installation script"
echo_script_status 0 "$scriptname"

activate_ntp() {
  echo_fn_status 0 ${FUNCNAME[0]}

  timedatectl set-ntp on

  echo_fn_status 1 ${FUNCNAME[0]}
}

install_pkg_pacman() {
  echo_fn_status 0 ${FUNCNAME[0]}

  sudo pacman -S --needed - < $dir/list-pkg-pacman 

  echo_fn_status 1 ${FUNCNAME[0]}
}

install_pkg_aur() {
  echo_fn_status 0 ${FUNCNAME[0]}

  if ! command -v yay &> /dev/null; then
    temp_path=$(mktemp -d)
    git clone https://aur.archlinux.org/yay.git $temp_path
    cd $temp_path
    makepkg -si
    cd $HOME
  fi
  yay -S --needed - < $dir/list-pkg-aur

  echo_fn_status 1 ${FUNCNAME[0]}
}

install_st() {
  echo_fn_status 0 ${FUNCNAME[0]}

  temp_path=$(mktemp -d)
  git clone https://github.com/andis-sprinkis/st.git $temp_path
  cd $temp_path
  git checkout 73c034ba05101e2fc337183af1cdec5bfe318b99
  sudo make install
  cd $HOME

  echo_fn_status 1 ${FUNCNAME[0]}
}

install_node_lts() {
  echo_fn_status 0 ${FUNCNAME[0]}

  mkdir -p $HOME/.nvm
  export NVM_DIR=$HOME/.nvm
  . /usr/share/nvm/nvm.sh
  nvm install lts/fermium
  nvm use lts/fermium
  nvm alias default lts/fermium

  echo_fn_status 1 ${FUNCNAME[0]}
}

install_otf_cascadia_code() {
  echo_fn_status 0 ${FUNCNAME[0]}

  temp_path=$(mktemp -d)
  cd $temp_path
  wget https://github.com/microsoft/cascadia-code/releases/download/v2008.25/CascadiaCode-2008.25.zip &&
  unzip $temp_path/CascadiaCode-2008.25.zip -d $temp_path/unzip
  mkdir -p $HOME/.fonts/CascadiaCode-2008.25/otf/*
  cp -rv $temp_path/unzip/otf/* $HOME/.fonts/CascadiaCode-2008.25/otf/
  cd $HOME

  echo_fn_status 1 ${FUNCNAME[0]}
}

change_shell() {
  echo_fn_status 0 ${FUNCNAME[0]}

  chsh -s /bin/zsh $cf_username 

  echo_fn_status 1 ${FUNCNAME[0]}
}

install_dotfile() {
  echo_fn_status 0 ${FUNCNAME[0]}

  temp_path=$(mktemp -d)
  git clone --separate-git-dir=$HOME/.dotfiles-git https://github.com/andis-sprinkis/linux-user-config $temp_path
  rsync --recursive --verbose --exclude '.git' $temp_path/ $HOME
  git --git-dir=$HOME/.dotfiles-git/ --work-tree=$HOME config --local status.showUntrackedFiles no
  [ ! -d $HOME/.config ] && mkdir -p $HOME/.config
  git clone https://github.com/andis-sprinkis/neovim-user-config $HOME/.config/nvim

  echo_fn_status 1 ${FUNCNAME[0]}
}

enable_vboxservice() {
  echo_fn_status 0 ${FUNCNAME[0]}

  if ! systemctl is-active --quiet vboxservice.service; then
    systemctl enable --now vboxservice.service
  fi

  echo_fn_status 1 ${FUNCNAME[0]}
}

install_user_cfg() {
  activate_ntp
  install_pkg_pacman
  install_pkg_aur
  install_st
  install_node_lts
  install_otf_cascadia_code
  install_dotfile
  enable_vboxservice
  change_shell
}

install_user_cfg

echo_script_status 1 "$scriptname"
