#!/usr/bin/env sh
set -e
dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
. $dir/../common/util
. $dir/../config
scriptname="Post system installation script"
echo_script_status 0 "$scriptname"

activate_ntp() {
  echo_fn_status 0 ${FUNCNAME[0]}

  timedatectl set-ntp on

  echo_fn_status 1 ${FUNCNAME[0]}
}

enable_vboxservice() {
  echo_fn_status 0 ${FUNCNAME[0]}

  if ! systemctl is-active --quiet vboxservice.service; then
    systemctl enable --now vboxservice.service
  fi

  echo_fn_status 1 ${FUNCNAME[0]}
}

clean_zshrc() {
  tmp=$(mktemp)
  head -n -1 /home/${cf_username}/.zshrc > $tmp && mv $tmp /home/${cf_username}/.zshrc
}

fn() {
  activate_ntp
  enable_vboxservice
  clean_zshrc
}

fn

echo_script_status 1 "$scriptname"
