#!/usr/bin/env bash
set -e

# Please review these settings...

cf_hostname=arch-00
cf_username=user-00
cf_timezone=Europe/Riga
cf_locale_gen=\
"en_US.UTF-8 UTF-8
lv_LV.UTF-8 UTF-8
"
cf_locale_conf=\
"LANG=en_US.UTF-8
LC_TIME=lv_LV.UTF-8
LC_MEASUREMENT=lv_LV.UTF-8
LC_MONETARY=lv_LV.UTF-8
LC_NUMERIC=lv_LV.UTF-8
LC_PAPER=lv_LV.UTF-8
"
cf_pacman_mirror_country=Latvia,Lithuania,Estonia,Finland,Sweden,Russia
cf_pacman_mirror_count=10
cf_dev_partition_boot=/dev/sda1
cf_dev_partition_root=/dev/sda2
cf_dev_partition_home=/dev/sdb1
cf_dev_partition_var=/dev/sdc1
cf_mkfs_main_file_system=ext4
cf_swap_M_count=4096
cf_is_vbox_guest=1
cf_user_mnt_dirs="/mnt/nvme{1..5} /mnt/sata{1..5} /mnt/usb{1..5} /mnt/pc{1..5} /mnt/nas{1..5} /mnt/vm{1..5} /mnt/mobile{1..5}"
cf_user_config_init_script_url=https://raw.githubusercontent.com/andis-sprinkis/nix-user-config/master/.local/bin/init_nix_user_config
cf_user_config_init_script_args=--with-nvim-config
cf_nvm_default_nodejs_version=lts/fermium
