#!/usr/bin/env sh
set -e
dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
. $dir/util
. $dir/config

install_pkg_aur() {
  echo_fn_status 0 ${FUNCNAME[0]}

  if ! command -v yay &> /dev/null; then
    temp_path=$(mktemp -d)
    git clone https://aur.archlinux.org/yay.git $temp_path
    cd $temp_path
    makepkg -si
    cd $HOME
  fi
  yay -S --needed - < $dir/package-lists/list-pkg-aur

  echo_fn_status 1 ${FUNCNAME[0]}
}

install_dotfile() {
  echo_fn_status 0 ${FUNCNAME[0]}

  temp_path=$(mktemp -d)
  git clone --separate-git-dir=$HOME/.dotfiles-git https://github.com/andis-sprinkis/linux-user-config $temp_path
  rsync --recursive --verbose --exclude '.git' $temp_path/ $HOME
  git --git-dir=$HOME/.dotfiles-git/ --work-tree=$HOME config --local status.showUntrackedFiles no
  [ ! -d $HOME/.config ] && mkdir -p $HOME/.config
  git clone https://github.com/andis-sprinkis/neovim-user-config $HOME/.config/nvim

  echo_fn_status 1 ${FUNCNAME[0]}
}

install_otf_cascadia_code() {
  echo_fn_status 0 ${FUNCNAME[0]}

  temp_path=$(mktemp -d)
  cd $temp_path
  wget https://github.com/microsoft/cascadia-code/releases/download/v2008.25/CascadiaCode-2008.25.zip &&
  unzip $temp_path/CascadiaCode-2008.25.zip -d $temp_path/unzip
  mkdir -p $HOME/.fonts/CascadiaCode-2008.25/otf/*
  cp -rv $temp_path/unzip/otf/* $HOME/.fonts/CascadiaCode-2008.25/otf/
  cd $HOME

  echo_fn_status 1 ${FUNCNAME[0]}
}

install_node_lts() {
  echo_fn_status 0 ${FUNCNAME[0]}

  mkdir -p $HOME/.nvm
  export NVM_DIR=$HOME/.nvm
  . /usr/share/nvm/nvm.sh
  nvm install lts/fermium
  nvm use lts/fermium
  nvm alias default lts/fermium

  echo_fn_status 1 ${FUNCNAME[0]}
}

set_post_reboot_script() {
  echo_fn_status 0 ${FUNCNAME[0]}

  echo "sudo /linux-instal/post-reboot" >> /home/${cf_username}/.zshrc

  echo_fn_status 1 ${FUNCNAME[0]}
}

fn() {
  install_pkg_aur
  install_dotfile
  install_otf_cascadia_code
  install_node_lts
  set_post_reboot_script
  exit
}

fn
