#!/usr/bin/env sh
set -e
dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
. $dir/util
. $dir/config
scriptname="Post system installation script"
echo_script_status 0 "$scriptname"

activate_ntp() {
  echo_fn_status 0 ${FUNCNAME[0]}

  sudo timedatectl set-ntp on

  echo_fn_status 1 ${FUNCNAME[0]}
}

enable_vboxservice() {
  echo_fn_status 0 ${FUNCNAME[0]}

  if ! systemctl is-active --quiet vboxservice.service; then
    sudo systemctl enable --now vboxservice.service
  fi

  echo_fn_status 1 ${FUNCNAME[0]}
}

cleanup_zshrc() {
  echo_fn_status 0 ${FUNCNAME[0]}

  tmp=$(mktemp)
  path_zshrc=/home/${cf_username}/.zshrc
  head -n -1 $path_zshrc > $tmp && mv $tmp $path_zshrc

  echo_fn_status 0 ${FUNCNAME[1]}
}

fn() {
  activate_ntp
  enable_vboxservice
  cleanup_zshrc
}

fn

echo_script_status 1 "$scriptname"
