#!/usr/bin/env sh
set -e

echo "Pre-installation script has started..."; echo
echo

rm -rf /var/lib/pacman/sync
pacman --noconfirm -Sy git vi
git clone https://github.com/andis-sprinkis/linux-install /linux-install

echo "Pre-installation script has finished!"; echo
echo
echo "Please double-check /linux-install/main file and then run /linux-install/main to start installation."
