#!/usr/bin/env sh
set -e

# ------------------------------------------------------------------------------

echo "
System upgrade:
"
yay -Syu

# ------------------------------------------------------------------------------

[ -s "./pkg_pacman" ] && {
  echo "
Arch package repository packages installation:
"
  yay -S --needed $(echo $(< "./pkg_base")) $(echo $(< "./pkg_pacman"))
}

# ------------------------------------------------------------------------------

[ -s "./pkg_yay" ] && {
  echo "
AUR packages installation:
"
  yay -S --needed $(echo $(< "./pkg_aur"))
}

# ------------------------------------------------------------------------------

[ -s "./pkg_appimage" ] && {
  echo "
AppImage packages installation:
"

  for p in $(echo $(< "./pkg_appimage")); do
      curl --location --no-clobber --output-dir "$HOME/.local/opt/appimage" --remote-name "$p"
  done

  chmod +x $HOME/.local/opt/appimage/*
}

# ------------------------------------------------------------------------------

[ -s "./pkg_pypi" ] && {
  echo "
PyPI packages installation:
"
  for p in $(echo $(< "./pkg_pypi")); do pipx install $p; done
}

# ------------------------------------------------------------------------------

[ -s "./pkg_npm" ] && {
  echo "
NPM packages installation:
"
  volta install $(echo $(< "./pkg_npm"))
}
