#!/usr/bin/env sh
set -eu

# ------------------------------------------------------------------------------

echo "
System upgrade:
"
yay --color=auto -Syu

# ------------------------------------------------------------------------------

[ -s "./pkg_pacman" ] && {
  echo "
Arch package repository packages installation:
"
  yay --color=auto -S --needed $(echo $(cat "./pkg_base")) $(echo $(cat "./pkg_pacman"))
}

# ------------------------------------------------------------------------------

[ -s "./pkg_yay" ] && {
  echo "
AUR packages installation:
"
  yay --color=auto -S --needed $(echo $(cat "./pkg_aur"))
}

# ------------------------------------------------------------------------------

# [ -s "./pkg_appimage" ] && {
#   echo "
# AppImage packages installation:
# "
#
#   for p in $(echo $(cat "./pkg_appimage")); do
#     curl --location --no-clobber --output-dir "$HOME/.local/opt/appimage" --remote-name "$p"
#   done
#
#   chmod +x $HOME/.local/opt/appimage/*
# }

# ------------------------------------------------------------------------------

[ -s "./pkg_pypi" ] && {
  echo "
PyPI packages upgrade:
"
  pipx upgrade-all

  echo "
PyPI packages installation:
"
  for p in $(echo $(cat "./pkg_pypi")); do pipx install "$p"; done
}

# ------------------------------------------------------------------------------

[ -s "./pkg_npm" ] && {
  echo "
NPM packages installation:
"
  volta install $(echo $(cat "./pkg_npm"))
}
