#!/usr/bin/env sh
set -e
dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
. $dir/../common/util
scriptname="System installation script"
echo_script_status 0 "$scriptname"

fn() {
  $dir/pre-chroot
  arch-chroot /mnt /linux-install/os-install/on-chroot
}

fn

echo_script_status 1 "$scriptname"
echo_br_bottom "Please reboot (systemctl reboot) and run /linux-install/post-os-install/install to continue with installing the user packages and configuration!"
