#!/usr/bin/env sh
set -e
dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
. $dir/../config
. $dir/../common/util

format_partitions() {
  echo_fn_status 0 ${FUNCNAME[0]}

  mkfs.vfat -F32 $cf_boot_partition
  mkfs.$cf_mkfs_format_system_partition $cf_system_partition

  echo_fn_status 1 ${FUNCNAME[0]}
}

mount_partitions() {
  echo_fn_status 0 ${FUNCNAME[0]}

  mount $cf_system_partition /mnt
  mkdir /mnt/boot
  mount $cf_boot_partition /mnt/boot

  echo_fn_status 1 ${FUNCNAME[0]}
}

sort_pacman_mirrors() {
  echo_fn_status 0 ${FUNCNAME[0]}

  reflector --country $cf_pacman_mirror_country --protocol https --latest 5 --save /etc/pacman.d/mirrorlist

  echo_fn_status 1 ${FUNCNAME[0]}
}

install_base_packages() {
  echo_fn_status 0 ${FUNCNAME[0]}

  echo "/mnt $cf_base_packages" | xargs pacstrap

  echo_fn_status 1 ${FUNCNAME[0]}
}

generate_fstab() {
  echo_fn_status 0 ${FUNCNAME[0]}

  genfstab -U /mnt >> /mnt/etc/fstab

  echo_fn_status 1 ${FUNCNAME[0]}

}

cp_install_files_root() {
  echo_fn_status 0 ${FUNCNAME[0]}

  cp -rv $dir/.. /mnt/linux-install

  echo_fn_status 1 ${FUNCNAME[0]}
}

fn() {
  format_partitions
  mount_partitions
  sort_pacman_mirrors
  install_base_packages
  generate_fstab
  cp_install_files_root
}

fn
